Adding general little things
oresat/oresat-linux-updater pull request #12
Opened 2021-03-14 03:26 UTC by mairacanal

Closes #7 

Just adding the command argument for add olu-status tar files to the olu-status cache and the option to move generate updates to the update cache after calling make in the cli.

2021-03-15 20:10 UTC, ryanpdx requested changes
Looks good.

Just a quick change as I don't think the add cache functionality belongs in the `UpdateMaker` class.

Also since this is now using `ArgumentParser` could you change it so `usage()` is only the cli usage message and is only called when `help` is entered in the CLI. Then `ArguementParser` can print out its program help message.

2021-03-15 21:17 UTC, mairacanal commented on update_maker/update_maker.py
> +        # add olu-status tar files to the olu-status cache
I did this to make it possible the command `python3 -m update_maker generic --add ./tests/test_files/generic_olu-status_1614805451.tar.xz`. If I put this outside of the `UpdateMaker` class, it won't be possible to run this command the first time. You will have to run the following commands:

`
python3 -m update_maker --add ./tests/test_files/generic_olu-status_1614805451.tar.xz
python3 -m update_maker generic
`

So what do you think is better?

2021-03-15 22:47 UTC, ryanpdx commented on update_maker/update_maker.py
> +        # add olu-status tar files to the olu-status cache
Or as a member in the `UpdateMaker` class. Just not in `__init__()`.

2021-03-16 19:39 UTC, ryanpdx approved these changes
Looks good!

2021-03-16 19:40 UTC, merged